"""add last_summary_timestamp to chats table

Revision ID: 2aec5090bdd8
Revises: 41548e099c5f
Create Date: 2025-04-04 11:07:19.328406+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aec5090bdd8'
down_revision: Union[str, None] = '41548e099c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_summary_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_summary_timestamp')
    # ### end Alembic commands ### 