"""create chat_stats table

Revision ID: create_chat_stats
Revises: 20250404_1140_9606bc129069_remove_is_active_column_from_chats_table
Create Date: 2024-04-04 19:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'create_chat_stats'
down_revision: Union[str, None] = '20250404_1140_9606bc129069_remove_is_active_column_from_chats_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('chat_type', sa.String(), nullable=False),
        sa.Column('is_silent', sa.Boolean(), nullable=False),
        sa.Column('response_probability', sa.Float(), nullable=False),
        sa.Column('smart_mode', sa.Boolean(), nullable=False),
        sa.Column('importance_threshold', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_summary_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ### 