services:
  - type: background
    name: superbot
    env: python
    region: frankfurt  # или другой регион по вашему выбору
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      cd /opt/render/project/src && python -m alembic upgrade head
    startCommand: python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: superbot_db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false 