services:
  - type: background
    name: superbot
    env: python
    region: frankfurt  # или другой регион по вашему выбору
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false 