services:
  - type: background
    name: superbot
    env: python
    region: frankfurt  # или другой регион по вашему выбору
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "Checking project structure..."
      ls -la /opt/render/project/src
      echo "Checking migrations directory..."
      ls -la /opt/render/project/src/src/database/migrations/versions
      echo "Running database migrations..."
      cd /opt/render/project/src
      echo "Current directory: $(pwd)"
      echo "Python path: $PYTHONPATH"
      echo "Listing migrations..."
      python -m alembic history
      echo "Current migration version..."
      python -m alembic current
      echo "Running upgrade..."
      PYTHONPATH=/opt/render/project/src python -m alembic -v upgrade head
    startCommand: PYTHONPATH=/opt/render/project/src python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: superbot_db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false 