services:
  - type: background
    name: superbot
    env: docker
    region: frankfurt  # или другой регион по вашему выбору
    plan: free
    branch: main
    buildCommand: |
      cp apply_migrations.sh /opt/render/project/src/
      chmod +x /opt/render/project/src/apply_migrations.sh
    startCommand: python src/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false 